<br /><br />
<div class="container text-primary">
<div id="view-content">

    <div class="jumbotron col-sm-1-offset-1 ">

                        <h3>login</h3>

                        <div class="form-group-lg"></div>

                        <form  method="post" action="" class="form-horizontal">
                            <div class="form-group">

                            </div>
                            <div class="form-group">
                                <div class="col-sm-10">
                                    <?php
                                    echo $this->login;
                                    ?> 
                                </div>
                            </div>

                            

                        </form>
        </div>
    </div>
</body>
</html>